import { Types } from 'mongoose';

const SAIBAN_TABLETS_ID = new Types.ObjectId('6437187b6a285129dc61df44');
const SAIBAN_DROPS_ID = new Types.ObjectId('6437187b6a285129dc61df45');
const SAIBAN_SYRUPS_ID = new Types.ObjectId('6437187b6a285129dc61df46');

export const products = [
  // Saiban Syrups Products
  {
    name: 'ALFAFIT 120ml',
    shortDescription: 'Tonic/ Energatic Digestive',
    urduDescription: 'اعصابی طاقت نظام ہضم کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'ALFAFIT 240ml',
    shortDescription: 'Tonic/ Energatic Digestive',
    urduDescription: 'اعصابی طاقت نظام ہضم کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 240,
    packType: 'ml',
    price: 250,
  },
  {
    name: 'BRONCOFIT 120ml',
    shortDescription: 'Cough Syrup',
    urduDescription: 'ہرقسم کی کھانسی کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'Fever Fit 120ml',
    shortDescription: 'For Fever',
    urduDescription: 'ہر قسم کے بخار کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'Liver Fit 120ml',
    shortDescription: 'Liver Tonic',
    urduDescription: 'جگر کے جملہ امراض کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'Liver Fit 240ml',
    shortDescription: 'Liver Tonic',
    urduDescription: 'جگر کے جملہ امراض کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 240,
    packType: 'ml',
    price: 250,
  },
  {
    name: 'Tonsi Fit 120ml',
    shortDescription: 'Tonsillitis Fever Glandular Swelling',
    urduDescription: 'ٹانسلز گلے کے غدودوں کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'Gastro Fit 120ml',
    shortDescription: 'Gastric Problems',
    urduDescription: 'گیس تیزابیت پیٹ درد کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'Gastro Fit 240ml',
    shortDescription: 'Gastric Problems',
    urduDescription: 'گیس تیزابیت پیٹ درد کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 240,
    packType: 'ml',
    price: 250,
  },
  {
    name: 'iRO Fit 240ml',
    shortDescription: 'iron Tonic',
    urduDescription: 'خون کی کمی کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 240,
    packType: 'ml',
    price: 250,
  },
  {
    name: 'SLim Fit 120ml',
    shortDescription: 'Super Fitness',
    urduDescription: 'موٹاپااور وزن کم کرنے کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 250,
  },
  {
    name: 'Toot Siah 120ml',
    shortDescription: 'Sore Thorat Cough & Catarrh',
    urduDescription: 'گلا خراب کیرے کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'Sharbat-E-Podina 120ml',
    shortDescription: 'Indigestion, Acidity Flatulance',
    urduDescription: 'بدہضمی تیزابیت اپھارہ کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 120,
    packType: 'ml',
    price: 170,
  },
  {
    name: 'Sharbat-E-Podina 240ml',
    shortDescription: 'Indigestion, Acidity Flatulance',
    urduDescription: 'بدہضمی تیزابیت اپھارہ کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 240,
    packType: 'ml',
    price: 250,
  },
  {
    name: 'GN-KSA 240ml',
    shortDescription: 'For Brain & Nerves',
    urduDescription: 'دماغی کمزوری ڈپریشن پھٹوں کا کھچاؤ سن ہونا',
    quantity: 0,
    categoryId: SAIBAN_SYRUPS_ID,
    size: 240,
    packType: 'ml',
    price: 390,
  },

  // Saiban Drops Products
  {
    name: 'infectionHit 20ml',
    shortDescription: 'Infection inflammation',
    urduDescription: 'ھر قسم کی انفیکشن سوزش سوجن کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'SkinSA 20ml',
    shortDescription: 'Allergy & Skin Problems',
    urduDescription: 'ھر قسم کی الرجی جلدی امراض کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'SinuSA 20ml',
    shortDescription: 'Sinusitis & Flu',
    urduDescription: 'ناک کی ہڈی کی سوزش نزلہ زکا کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'StomSA 20ml',
    shortDescription: 'FlatuLence',
    urduDescription: 'گیس اپھارہ پیٹ درد کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'URACSA 20ml',
    shortDescription: 'For Gout Pain & UricAcid',
    urduDescription: 'جوڑوں کا درد یورک ایسڈکیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'BRonSa 20ml',
    shortDescription: 'Phlegm Asthma Allergy',
    urduDescription: 'کیرا بلخم دمہ الرجی کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'CalcuLiSA 20ml',
    shortDescription: 'Removes Kidny Stones',
    urduDescription: 'گردے کی پتھری کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'DiA Hit 20ml',
    shortDescription: 'For Diabetes',
    urduDescription: 'شوگر کے خاتمے  کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'HyperSA 20ml',
    shortDescription: 'HyperTension',
    urduDescription: 'ھائ بلڈ پریشر کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 195,
  },
  {
    name: 'iDeal Ginseng 20ml',
    shortDescription: 'Low Sperms Count Impotency',
    urduDescription: 'سپرم کی کمی مردانہ کمزوری کیلۓ ',
    quantity: 0,
    categoryId: SAIBAN_DROPS_ID,
    size: 20,
    packType: 'ml',
    price: 250,
  },

  // Saiban Tablets Products
  {
    name: 'Ener-Z. 30Tabs',
    shortDescription: 'Energy & immunity',
    urduDescription: 'پٹھوں اور اعصابی کمزوری کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 30,
    packType: 'Tabs',
    price: 390,
  },
  {
    name: 'PiRit 20Tabs',
    shortDescription: 'For Piles',
    urduDescription: 'ہر قسم کی بواسیر کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 20,
    packType: 'Tabs',
    price: 260,
  },
  {
    name: 'DiAHiT 20Tabs',
    shortDescription: 'For Diabetes',
    urduDescription: 'شوگر کے خاتمے کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 20,
    packType: 'Tabs',
    price: 250,
  },
  {
    name: 'LeucoSA 20Tabs',
    shortDescription: 'For LeucoSA',
    urduDescription: 'لیکوریا کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 20,
    packType: 'Tabs',
    price: 250,
  },
  {
    name: 'Bed PLaSA 30Tabs',
    shortDescription: 'For bed Wetting',
    urduDescription: 'پیشاب کانکل جانا سوتے جاگتے',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 30,
    packType: 'Tabs',
    price: 180,
  },
  {
    name: 'Fever Hit 30Tabs',
    shortDescription: 'For Fever',
    urduDescription: 'ہرقسم کے بخار کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 30,
    packType: 'Tabs',
    price: 180,
  },
  {
    name: 'Pain hit 30Tabs',
    shortDescription: 'For Pain',
    urduDescription: 'ہر قسم کے درد کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 30,
    packType: 'Tabs',
    price: 180,
  },
  {
    name: 'ideaL Ginseng 20Tabs',
    shortDescription: 'Low Sperms Count Impotency',
    urduDescription: 'سپرم کی کمی مردانہ کمزوری کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 20,
    packType: 'Tabs',
    price: 250,
  },
  {
    name: 'H-PyLoriSA 20Tabs',
    shortDescription: 'For H-PyLori Gut Disorders',
    urduDescription: 'ایچ-پائیلوری اور معدے کےامراض کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 20,
    packType: 'Tabs',
    price: 250,
  },
  {
    name: 'BioSA 21 30Tabs',
    shortDescription: 'Teething Troubles',
    urduDescription: 'بچوں کے دانت نکلنے میں اسانی کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 30,
    packType: 'Tabs',
    price: 250,
  },
  {
    name: 'FlunSA 30Tabs',
    shortDescription: 'For Flu',
    urduDescription: 'موسمی نزلہ زکام چھینکیں کھانسی انفیکشن کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 30,
    packType: 'Tabs',
    price: 180,
  },
  {
    name: 'FemenSA 30Tabs',
    shortDescription: 'For Menstrual Troubles',
    urduDescription: 'ماہواری کی تکالیف دور کرنے کیلۓ',
    quantity: 0,
    categoryId: SAIBAN_TABLETS_ID,
    size: 30,
    packType: 'Tabs',
    price: 290,
  },
];
