#!/bin/sh

# Get the name of the branch being committed to
branch_name=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

# Check if the branch is main or dev
if [ "$branch_name" = "main" ] || [ "$branch_name" = "dev" ] || [ "$branch_name" = "master" ] ; then
  echo "Pushing to $branch_name branch is not allowed. Create a branch and make a pull request instead."
  exit 1
fi

# Disable concurent to run `check-types` after ESLint in lint-staged
# cd "$(dirname "$0")/.." && npx --no lint-staged --concurrent false
